# Generated by Django 5.1.4 on 2025-04-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service_of_interest', models.CharField(choices=[('Consultancy', 'Consultancy'), ('Engineering', 'Engineering'), ('Project Management', 'Project Management'), ('Supply Chain Management', 'Supply Chain Management'), ('Learning and Development', 'Learning and Development')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
