# Generated by Django 5.1.4 on 2025-04-13 00:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_description', models.TextField(blank=True)),
                ('application_name', models.CharField(max_length=255)),
                ('application_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'License Key',
                'verbose_name_plural': 'License Keys',
                'ordering': ['-issued_date'],
            },
        ),
    ]
