# Generated by Django 5.1.4 on 2025-05-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reported_by',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
